# -*- coding: utf-8 -*-
"""crime

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddtQLeaOrv-QNkAU8IRSNxfXVx8uEU1X
"""

import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('/Crimes_-_2001_to_Present.csv', index_col=['Date'])

df.shape

df.head()

df['Date'] = pd.to_datetime(df.index)
df['Date_year'] = df.Date.map(lambda x:x.year)
df['Date_month'] = df.Date.map(lambda x:x.month)
df['Date_day'] = df.Date.map(lambda x:x.day)
df['Date_hour'] = df.Date.map(lambda x:x.hour)
df['Date_minute'] = df.Date.map(lambda x:x.minute)
df['Date_weekday'] = df.Date.map(lambda x:x.dayofweek)

df['Primary Type'].value_counts().plot.bar()
plt.title("Crimes")
plt.show()

df['Location Description'].value_counts()[:10].plot.bar()
plt.title("Crimes")
plt.show()

def fn_barplot(data, col):
  if data[col].dtype in ['object']:
    fig, ((ax1, ax2)) = plt.subplots(2, 1, figsize=(15, 2))

    plot_df = df[['Arrest',col]].dropna()
    df_1 = plot_df.loc[plot_df['Arrest']==True]
    df_2 = plot_df.loc[plot_df['Arrest']==False]

    df_1.groupby(col)[col].count().nlargest(10).plot(kind='barh', ax=ax1, title='Arrest: ' + col)
    df_2.groupby(col)[col].count().nlargest(10).plot(kind='barh', ax=ax2, title='No Arrest: ' + col)
    return plt.show()

